//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolverEcuacionCuadratica.Test.Wcf.SREcuacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SREcuacion.IResolverEcuacionCuadratica")]
    public interface IResolverEcuacionCuadratica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResolverEcuacionCuadratica/resolverLaEcuacionCuadratica", ReplyAction="http://tempuri.org/IResolverEcuacionCuadratica/resolverLaEcuacionCuadraticaRespon" +
            "se")]
        ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaResponse resolverLaEcuacionCuadratica(ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResolverEcuacionCuadratica/resolverLaEcuacionCuadratica", ReplyAction="http://tempuri.org/IResolverEcuacionCuadratica/resolverLaEcuacionCuadraticaRespon" +
            "se")]
        System.Threading.Tasks.Task<ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaResponse> resolverLaEcuacionCuadraticaAsync(ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resolverLaEcuacionCuadratica", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class resolverLaEcuacionCuadraticaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double Primer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double Segundo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double Tercer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double Discriminante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double Raiz1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double Raiz2;
        
        public resolverLaEcuacionCuadraticaRequest() {
        }
        
        public resolverLaEcuacionCuadraticaRequest(double Primer, double Segundo, double Tercer, double Discriminante, double Raiz1, double Raiz2) {
            this.Primer = Primer;
            this.Segundo = Segundo;
            this.Tercer = Tercer;
            this.Discriminante = Discriminante;
            this.Raiz1 = Raiz1;
            this.Raiz2 = Raiz2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resolverLaEcuacionCuadraticaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class resolverLaEcuacionCuadraticaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double Raiz1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double Raiz2;
        
        public resolverLaEcuacionCuadraticaResponse() {
        }
        
        public resolverLaEcuacionCuadraticaResponse(double Raiz1, double Raiz2) {
            this.Raiz1 = Raiz1;
            this.Raiz2 = Raiz2;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResolverEcuacionCuadraticaChannel : ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.IResolverEcuacionCuadratica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResolverEcuacionCuadraticaClient : System.ServiceModel.ClientBase<ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.IResolverEcuacionCuadratica>, ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.IResolverEcuacionCuadratica {
        
        public ResolverEcuacionCuadraticaClient() {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResolverEcuacionCuadraticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaResponse ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.IResolverEcuacionCuadratica.resolverLaEcuacionCuadratica(ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest request) {
            return base.Channel.resolverLaEcuacionCuadratica(request);
        }
        
        public void resolverLaEcuacionCuadratica(double Primer, double Segundo, double Tercer, double Discriminante, ref double Raiz1, ref double Raiz2) {
            ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest inValue = new ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest();
            inValue.Primer = Primer;
            inValue.Segundo = Segundo;
            inValue.Tercer = Tercer;
            inValue.Discriminante = Discriminante;
            inValue.Raiz1 = Raiz1;
            inValue.Raiz2 = Raiz2;
            ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaResponse retVal = ((ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.IResolverEcuacionCuadratica)(this)).resolverLaEcuacionCuadratica(inValue);
            Raiz1 = retVal.Raiz1;
            Raiz2 = retVal.Raiz2;
        }
        
        public System.Threading.Tasks.Task<ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaResponse> resolverLaEcuacionCuadraticaAsync(ResolverEcuacionCuadratica.Test.Wcf.SREcuacion.resolverLaEcuacionCuadraticaRequest request) {
            return base.Channel.resolverLaEcuacionCuadraticaAsync(request);
        }
    }
}
